TTTReborn/tttreborn

README.md
Just a few basic lines to direct users to the discord, and let them know the current stage of the project.
=> Update `README.md` with discord information

.editorconfig, .gitattributes, README.md, code/Game.ConVars.cs, code/Game.cs, code/gamemode/Inventory.cs, code/gamemode/Karma.cs, code/player/Body.cs, code/player/Player.Ammo.cs, code/player/Player.Clothes.cs, code/player/Player.Commands.cs, code/player/Player.cs, code/player/camera/SpectateCamera.cs, code/rounds/BaseRound.cs, code/rounds/PostRound.cs, code/rounds/PreRound.cs, code/ui/Crosshair.cs, code/ui/Hud.cs, code/ui/PlayerInfo.cs, code/ui/PlayerInfo.scss, code/weapons/AmmoType.cs, code/weapons/Knife.cs, code/weapons/Pistol.cs, code/weapons/SMG.cs, code/weapons/Shotgun.cs, code/weapons/ViewModel.cs, code/weapons/Weapon.cs
These additions are directly taken from dotnet runtime repository [1]. I did not go through all of them by hand so if you see something that you want to be handled differently ( e.g. naming styles, spaces ) please tell me.
All .editorconfig statements can be found in the microsoft documentation's language rules [2] and formatting rules [3].
[1] https://github.com/dotnet/runtime
[2] https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/language-rules
[3] https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules
=> Meta: Added codestyle to .editorconfig & format files

code/player/camera/SpectateCamera.cs, code/weapons/Pistol.cs
https://github.com/Facepunch/sbox-issues/discussions/337
=> Input: Fix regarding latest changes

code/player/Player.RPCs.cs, code/roles/BaseRole.cs, code/roles/InnocentRole.cs, code/roles/TraitorRole.cs, code/ui/InfoFeed.cs, code/ui/InfoFeed.scss, code/ui/InfoFeedEntry.cs, code/ui/PlayerInfo.scss
=> Hud: Reworked InfoFeed hud element

code/ui/PlayerInfo.cs, code/ui/WeaponSelection.cs, code/weapons/Pistol.cs
We can change this if we dislike it, but, similar to TTT2, show the ammo reserve in the HUD.
=> Fea: Show ammo reserve

code/player/Player.cs, code/ui/InspectMenu.cs, code/ui/InspectMenu.scss
Fixed continous netstream (replaced by RPC triggers) and improved design.
After pressing `E`:
=> HUD: InspectMenu rework

code/Game.Util.cs, code/player/Player.RPCs.cs, code/player/Player.cs, code/player/camera/SpectateCamera.cs, code/rounds/PostRound.cs
Just some general fixes / changes before we release.
=> Bug: General fixes

code/ui/Hud.cs, code/ui/Nameplate.cs, code/ui/Nameplate.scss
=> Added working Nameplates (one while looking on another player)

code/ui/Nameplate.cs, code/weapons/Knife.cs, code/weapons/Pistol.cs, code/weapons/SMG.cs, code/weapons/Shotgun.cs, code/weapons/Weapon.cs
This should make the game more "enjoyable" and prevent a scroll-lock shooting bug
=> Game: Adjusted damage, nameplate tracing and weapon switch shooting delay

code/gamemode/Game.cs, code/items/weapons/Pistol.cs, code/items/weapons/SMG.cs, code/items/weapons/Shotgun.cs, code/player/Inventory.cs, code/player/TTTPlayer.cs, code/rounds/BaseRound.cs, code/rounds/InProgressRound.cs, code/ui/GameTimer.cs, code/ui/GameTimer.scss, code/ui/QuickShop.cs, code/ui/QuickShop.scss, code/ui/WeaponSelection.cs
Fixed:
- Headshot damage scaling
- Shop item selection
- WinScreen display order
- Damage prevention outside `InProgressRound`
- Ammo stacking after each round (now cleared with `Inventory.DeleteContents()`)
- GameTimer inconsistencies
- `Game.Round` was `null` in edge-cases
=> Fixes: Several game bugs

code/gamemode/Game.cs, code/items/weapons/Pistol.cs, code/items/weapons/SMG.cs, code/items/weapons/Shotgun.cs, code/player/Inventory.cs, code/player/TTTPlayer.FallDamage.cs, code/player/TTTPlayer.cs, code/rounds/BaseRound.cs, code/rounds/InProgressRound.cs, code/ui/GameTimer.cs, code/ui/GameTimer.scss, code/ui/QuickShop.cs, code/ui/QuickShop.scss, code/ui/WeaponSelection.cs
Building on top of https://github.com/TTTReborn/ttt-reborn/pull/37
=> Falldamage: Added Falldamage detection

code/gamemode/Game.cs, code/items/weapons/AmmoType.cs, code/items/weapons/Knife.cs, code/items/weapons/Pistol.cs, code/items/weapons/SMG.cs, code/items/weapons/Shotgun.cs, code/items/weapons/TTTWeapon.cs, code/player/TTTPlayer.Status.cs, code/player/TTTPlayer.cs, code/rounds/InProgressRound.cs, code/rounds/PreRound.cs, code/rounds/WaitingRound.cs
Fixes:
- Disabled just player damage in non `InProgressRound`s
- Added player healing on round start in `InProgressRound`
- Changed headshot detection using `HitboxGroup` instead of `HitboxIndex`
- Removed deprecated functions
- Added `player.IsValid()` checks in timers
- Disabled corpse confirming in `PreRound` (`WaitingRound`)
- Added role syncing for new connected players
=> Game: Several fixes

code/ui/Hud.cs, code/ui/InspectMenu.cs
Huds could still show after death, delete the ones we don't need.
=> Hud: Delete huds on death

code/player/TTTPlayer.Status.cs, code/rounds/BaseRound.cs, code/rounds/InProgressRound.cs, code/rounds/PostRound.cs
Fixes players who suicide in post round. Allows post round deaths to occur from other players (Not sure if people disagree, but personally it's pretty fun being able to kill after round)
=> Game: Fix post round deaths, allow post round deaths

code/gamemode/Game.cs, code/gamemode/Karma.cs, code/items/weapons/TTTWeapon.cs, code/player/PlayerCorpse.cs, code/player/TTTPlayer.Roles.cs, code/player/TTTPlayer.cs, code/rounds/PostRound.cs, code/ui/GameTimer.cs, code/ui/Scoreboard.cs
Currently, I'm waiting for a decision / feedback regarding https://github.com/Facepunch/sbox-issues/issues/388 as this defines whether we should rework the `Round` system into a manually net-synced system (string based `Round` syncing that survives hotloading) or not.
=> Fix: (Task) error handling, Hotloading issue with `NetworkedComponent`

code/ui/Scoreboard.scss
=> Add scoreboard entry bgs

code/ui/QuickShop.cs
=> `AddEvent` -> `AddEventListener`

code/player/TTTPlayer.Confirmation.cs, code/player/TTTPlayer.RPCs.cs, code/player/TTTPlayer.Roles.cs, code/player/TTTPlayer.cs, code/roles/TTTRole.cs, code/roles/TraitorRole.cs, code/ui/Hud.cs, code/ui/Scoreboard.cs, code/ui/Scoreboard.scss, code/ui/ScoreboardEntry.cs
The `MIA` is just shown for `Traitors` team currently.
=> Scoreboard: Added  `MIA` group

code/player/TTTPlayer.cs
Found this issue after a longer test-run :D
=> Scoreboard: Fixed MIA state reset

.addon, .gitignore
=> Change ref. https://github.com/Facepunch/sbox-issues/discussions/374

code/ui/PlayerInfo.scss, code/ui/Scoreboard.scss, code/ui/WeaponSelection.scss
Todays UI polish summary:
- Adjusted ammo color in PlayerInfo and WeaponSelection to ensure better contrast
- Adjusted font-weight and -size in WeaponSelection.
- Changed MIA color, adjusted other scoreboardGroup colors.
Before:
After:
(EDIT: I have reverted the color of the "Alive" scoreboardGroup)
=> UI polish #2

code/player/TTTPlayer.Ammo.cs, code/player/TTTPlayer.Clothes.cs, code/player/TTTPlayer.Commands.cs, code/player/TTTPlayer.Confirmation.cs, code/player/TTTPlayer.FallDamage.cs, code/player/TTTPlayer.Flashlight.cs, code/player/TTTPlayer.RPCs.cs, code/player/TTTPlayer.Roles.cs, code/player/TTTPlayer.Shop.cs, code/player/TTTPlayer.Status.cs, code/player/TTTPlayer.cs, code/roles/TraitorRole.cs, code/rounds/InProgressRound.cs, code/rounds/PostRound.cs
Regarding https://github.com/Facepunch/sbox-issues/discussions/347#discussioncomment-926731
=> Networking: Fixed networking issues

code/player/TTTPlayer.Flashlight.cs
Current result:
https://user-images.githubusercontent.com/11843790/124387892-878ecd80-dce0-11eb-901e-6ddc18a970fc.mov
// edit
Completely fixed clientside lags with latest commit.
=> Flashlight: Fixed clientside "lagging"

code/ui/InventorySelection.cs
Bad index being used last time.
=> Fix: keyboard inventory selection

code/player/Inventory.cs, code/player/TTTPlayer.RPCs.cs, code/ui/InventorySelection.cs
Base.DeleteContents already clears the list.
=> Fix: inventory selecting UI getting cleared

code/items/IBuyableItem.cs, code/items/equipments/TTTEquipment.cs, code/items/perks/TTTPerk.cs, code/items/weapons/TTTWeapon.cs, code/player/TTTPlayer.Shop.cs, code/ui/QuickShop.cs
Shop does not require created objects anymore (just for initialization)
=> Shop: Fixed weapon spawning

code/items/equipments/MagnetoStick.cs, code/player/PlayerCorpse.cs
- Add some prevention against prop killing
- Fix grabbing distance naming
- Fix player corpse rope spring naming
=> MagnetoStick: Fix rope behavior (not visual)

code/player/TTTPlayer.VoiceChat.cs, code/ui/generalhud/chat/ChatBox.cs
=> Chat: Added TeamChat

code/player/TTTPlayer.VoiceChat.cs
To use, you have to add a binding like this:
`bind b +teamvoicechat`
=> VoiceChat: Added key binding support to TeamVoiceChat

code/player/TTTPlayer.Commands.cs, code/player/TTTPlayer.cs, code/rounds/BaseRound.cs, code/rounds/InProgressRound.cs, code/rounds/PostRound.cs, code/rounds/PreRound.cs, code/ui/alivehud/quickshop/QuickShop.cs, code/ui/generalhud/scoreboard/Scoreboard.ScoreboardGroup.cs, code/ui/generalhud/scoreboard/Scoreboard.cs, code/ui/generalhud/scoreboard/Scoreboard.scss
=> Spectator: Added `ttt_forcespec`, ForcedSpectators, Spectator scoreboard group; Scoreboard and Respawn fixes

code/ui/generalhud/menu/Menu.cs, code/ui/generalhud/menu/Menu.scss, code/ui/generalhud/menu/MenuHeader.cs, code/ui/generalhud/menu/MenuHeader.scss
=> Menu UI: Added homebutton

code/items/ammo/BuckshotAmmo.cs, code/items/ammo/PistolAmmo.cs, code/items/ammo/SMGAmmo.cs, code/items/weapons/Knife.cs, code/items/weapons/Pistol.cs, code/items/weapons/SMG.cs, code/items/weapons/Shotgun.cs
Small quality of life item for Hammer, will automatically appear in generated fgd file.
=> Add Hammer.EditorModel attributes to weapons/ammo

code/items/perks/radar/RadarPoint.cs, code/ui/Crosshair.cs, code/ui/General.cs, code/ui/Hud.cs, code/ui/alivehud/damageindicator/DamageIndicator.cs, code/ui/alivehud/drowningindicator/DrowningIndicator.cs, code/ui/alivehud/quickshop/QuickShop.cs, code/ui/generalhud/chat/ChatBox.cs, code/ui/generalhud/chat/ChatEntry.cs, code/ui/generalhud/gametimer/GameTimer.cs, code/ui/generalhud/infofeed/InfoFeed.cs, code/ui/generalhud/infofeed/InfoFeedEntry.cs, code/ui/generalhud/inspectmenu/InspectMenu.cs, code/ui/generalhud/inventorywrapper/InventoryWrapper.cs, code/ui/generalhud/inventorywrapper/effects/Effect.cs, code/ui/generalhud/inventorywrapper/effects/Effects.cs, code/ui/generalhud/inventorywrapper/inventoryselection/InventorySelection.cs, code/ui/generalhud/nameplate/Nameplate.cs, code/ui/generalhud/playerinfo/PlayerInfo.cs, code/ui/generalhud/postroundmenu/PostRoundMenu.cs, code/ui/generalhud/scoreboard/Scoreboard.Header.cs, code/ui/generalhud/scoreboard/Scoreboard.ScoreboardGroup.cs, code/ui/generalhud/scoreboard/Scoreboard.TableHeader.cs, code/ui/generalhud/scoreboard/Scoreboard.cs, code/ui/generalhud/scoreboard/ScoreboardEntry.cs, code/ui/generalhud/voicechat/VoiceEntry.cs, code/ui/generalhud/voicechat/VoiceList.cs, code/ui/panelheader/PanelHeader.cs
I also set the IsShowing member variables everywhere that setClass("hide", true/false) was.
This is my first pull request and also first time using C#. I'm excited to help!
=> Add TTTPanel to all Panels

code/ui/components/dragdrop/Drag.cs, code/ui/components/dragdrop/Drag.scss, code/ui/components/dropdown/Dropdown.cs, code/ui/components/dropdown/Dropdown.scss, code/ui/components/dropdown/DropdownOption.cs, code/ui/components/keybind/Keybind.cs, code/ui/components/keybind/Keybind.scss, code/ui/components/modal/Modal.cs, code/ui/components/modal/dialogbox/DialogBox.cs, code/ui/components/modal/dialogbox/DialogBox.scss, code/ui/components/modal/fileselection/FileSelection.cs, code/ui/components/modal/fileselection/FileSelection.scss, code/ui/components/modal/fileselection/FileSelectionEntry.cs, code/ui/components/switch/Switch.cs, code/ui/generalhud/menu/Menu.cs, code/ui/generalhud/menu/Menu.scss, code/ui/richpanel/RichPanel.Resizeable.cs, code/ui/tttpanel/TTTPanel.cs
DropDown:
https://user-images.githubusercontent.com/11843790/128244537-a3bf0563-2c15-4fec-a075-e45a44c4504c.mp4
=> Added `Dropdown`, `Modal`, `DialogBox`, `Keybind` and `FileSelection` UI component

code/lang/Language.cs, code/lang/TTTLanguage.cs, code/player/TTTPlayer.Shop.cs, code/ui/components/translationlabel/TranslationLabel.cs
https://github.com/TTTReborn/tttreborn/pull/139
IDE caught these methods that will be used in the future as public
=> Fixes: Mark methods as public

code/ui/components/dragdrop/Drag.cs, code/ui/components/dragdrop/Drag.scss, code/ui/components/dropdown/Dropdown.cs, code/ui/components/tabs/Tab.cs, code/ui/components/tabs/Tabs.cs, code/ui/components/tabs/Tabs.scss, code/ui/generalhud/menu/Menu.cs, code/ui/generalhud/menu/Menu.scss, code/ui/generalhud/nameplate/Nameplate.cs, code/ui/tttpanel/TTTPanel.cs
=> UI: Added `Tabs` UI component

code/items/weapons/TTTWeapon.cs
=> Fix: Multiple bullet holes

code/global/Utils.cs, code/items/IBuyableItem.cs, code/items/equipments/MagnetoStick.cs, code/player/TTTPlayer.Nameplate.cs, code/player/TTTPlayer.Roles.cs, code/player/TTTPlayer.Shop.cs, code/player/camera/FirstPersonSpectatorCamera.cs, code/roles/TTTRole.cs, code/roles/TraitorRole.cs, code/ui/alivehud/quickshop/QuickShop.Content.cs, code/ui/alivehud/quickshop/QuickShop.Footer.cs, code/ui/alivehud/quickshop/QuickShop.cs
=> Shop: Added `Shop` type, server to client shop syncing and shop settings

code/lang/packs/en-US.json, code/player/PlayerCorpse.cs, code/ui/components/generic/Panel.scss, code/ui/generalhud/entityhint/EntityHintPanel.cs, code/ui/generalhud/inspecthint/InspectHint.cs
Fixes #224 
Feel free to style it differently.
=> Add basic inspect hint

code/rounds/BaseRound.cs
`Networked` is probably deprecated.
=> Change round to use NetworkedComponent

code/settings/Settings.cs, code/ui/generalhud/menu/Menu.Settings.Server.cs, code/ui/generalhud/menu/Menu.Settings.cs
This will fix a bug that gonna appear if the settings json string is getting too big.
=> Settings: Added partial settings syncing

code/events/TTTEvent.Player.cs, code/gamemode/Game.cs, code/gamemode/Karma.cs, code/global/RPCs.cs, code/items/equipments/MagnetoStick.cs, code/player/TTTPlayer.AFK.cs, code/player/TTTPlayer.Commands.Server.cs, code/player/TTTPlayer.RPCs.cs, code/player/TTTPlayer.Shop.cs, code/player/TTTPlayer.Spectating.cs, code/player/TTTPlayer.VoiceChat.cs, code/player/TTTPlayer.cs, code/rounds/InProgressRound.cs, code/teams/TTTTeam.cs, code/ui/generalhud/chat/ChatBox.cs, code/ui/generalhud/inspectmenu/InspectMenu.cs, code/ui/generalhud/nameplate/Nameplate.cs, code/ui/generalhud/scoreboard/Scoreboard.cs, code/ui/generalhud/scoreboard/ScoreboardEntry.cs, code/ui/generalhud/scoreboard/ScoreboardGroup.cs
Finally, we got rid of PlayerScore
=> Scoreboard: Fixed scoreboard and removed obsolete functions

code/player/TTTPlayer.cs, code/player/camera/FirstPersonSpectatorCamera.cs, code/player/camera/FreeSpectateCamera.cs, code/player/camera/RagdollSpectateCamera.cs, code/player/camera/ThirdPersonSpectateCamera.cs
Use the FOV in the settings menu of s&box everywhere.
=> Fea: s&box options FOV

code/items/equipments/Hands.GrabbableProp.cs
Fixes https://github.com/TTTReborn/tttreborn/issues/333
=> Bug: Fix weapon hands pickup

code/rounds/PreRound.cs
@Alf21 we can refactor this entire system once the visual scripting system is setup, for now we can just deal out the detective role like we do with the traitor. 
I might consider pinging Fires to get the code for the DNA system they started a while back.
=> Fea: Give out detective role

code/ui/alivehud/quickshop/QuickShop.scss
Closes https://github.com/TTTReborn/tttreborn/issues/361
=> Fix quickshop item

code/ui/generalhud/chat/ChatBox.cs
I don't really like the chatbox background, thoughts? The black background takes up a huge part of your screen when there is a long chat history.
=> Fea: Remove chatbox background

code/items/weapons/TTTWeapon.cs
We should look towards improving this similar to TTT2, but, for now let's just swap out the primary for ease of use.
=> Fea: Swap active weapons out

.addon
This file is now auto-generated by sbox
=> Fix: Upgrade to addon manager

code/items/ICarriableItem.cs, code/items/ShopItemData.cs, code/items/ammo/ShotgunAmmo.cs, code/items/ammo/SniperAmmo.cs, code/items/ammo/TTTAmmo.cs, code/items/equipments/C4Equipment.cs, code/items/equipments/DecoyEquipment.cs, code/items/equipments/Hands.cs, code/items/equipments/HealthStation.cs, code/items/equipments/TTTEquipment.cs, code/items/weapons/Knife.cs, code/items/weapons/NewtonLauncher.cs, code/items/weapons/Pistol.cs, code/items/weapons/SMG.cs, code/items/weapons/Shotgun.cs, code/items/weapons/TTTWeapon.cs, code/items/weapons/TTTWeaponRandom.cs, code/player/Inventory.cs, code/ui/generalhud/inventorywrapper/inventoryselection/InventorySelection.cs, config/neox.tttreborn.fgd
- BuckshotAmmo -> ShutgunAmmo
- Added SniperAmmo
- Improved Slot and Ammo handling (to avoid inconsistencies)
- Added possibility to spawn a weapon category on random spawns
=> Weapons: Improvements

code/player/Inventory.cs, code/player/TTTPlayer.Roles.cs, code/roles/TTTRole.cs, code/rounds/InProgressRound.cs, code/teams/NoneTeam.cs, code/teams/TTTTeam.cs
- Fixed never ending rounds due to ROLE_NONE
- Added improved win condition possibilities
=> Fix: Win conditions

code/visual-programming/nodes/PercentageSelectionStackNode.cs
RoleSelectionNode assigns every role minimum once now.
=> Fix: Minimum role distribution

code/items/IItem.cs, code/items/equipments/TTTEquipment.cs, code/items/perks/TTTPerk.cs, code/items/weapons/TTTWeapon.cs, code/lang/Language.cs, code/roles/TTTRole.cs, code/ui/alivehud/quickshop/QuickShop.cs, code/ui/generalhud/inventorywrapper/effects/Effect.cs, code/ui/generalhud/tttmenu/pages/shopeditorpage/ShopEditorPage.Item.Commands.cs, code/ui/visual-programming/Window.cs, code/ui/visual-programming/nodes/PercentageSelectionNode.cs, code/ui/visual-programming/nodes/PlayerAmountSelectionNode.cs, code/ui/visual-programming/nodes/RandomSelectionNode.cs, code/ui/visual-programming/nodes/node/Node.cs, code/visual-programming/NodeStack.Networking.cs, code/visual-programming/NodeStack.cs, code/visual-programming/nodes/PercentageSelectionStackNode.cs, code/visual-programming/nodes/PlayerAmountSelectionStackNode.cs, code/visual-programming/nodes/RandomSelectionStackNode.cs, code/visual-programming/nodes/StackNode.cs
- Improved dezerialization
- improved PercentageSelection
- Fixed GetTranslationKey issue
=> Cleanup: Cleanups and improvements

code/items/ICarriableItem.cs, code/items/IPickupable.cs, code/items/ammo/Ammo.cs, code/items/equipments/Equipment.cs, code/items/equipments/Hands.GrabbableCorpse.cs, code/items/equipments/Hands.GrabbableProp.cs, code/items/equipments/Hands.cs, code/items/weapons/Weapon.cs, code/map/MapHandler.cs, code/map/logicbutton/LogicButton.cs, code/player/TTTPlayer.cs
- Currently causes visual bugs...
=> Fea: Automatic Pickup-System

code/gameevents/base/GameEvent.cs, code/gameevents/player/DiedEvent.cs, code/gamemode/Game.cs, code/gamemode/Karma.cs, code/global/Utils.cs, code/items/weapons/base/Weapon.Var.cs, code/items/weapons/base/Weapon.cs, code/player/Player.Damage.cs, code/player/Player.Flashlight.cs, code/player/Player.cs, code/player/PlayerCorpse.cs, code/player/inventory/Inventory.cs, code/rounds/BaseRound.cs, code/ui/Hud.cs, code/ui/generalhud/scoreboard/Scoreboard.cs, code/ui/generalhud/scoreboard/Scoreboard.scss
- Karma cleanup
- Improved GameEvent
- Added autoreload to weapons
- Fixed viewing through walls
- Removed legacy Game's library
- Implemented Model.Load pattern
=> Fixes: Fixed GameEvent error due to s&box Client.All init delay and other fixes

code/gamemode/Game.cs, code/global/Utils.cs, code/player/Player.cs, code/ui/generalhud/chat/ChatBox.cs, code/ui/generalhud/tabmenu/scoreboard/Scoreboard.cs, code/ui/generalhud/tabmenu/scoreboard/ScoreboardEntry.cs, code/ui/generalhud/voicechat/VoiceChatEntry.cs
Changes regarding https://github.com/Facepunch/sbox-issues/issues/1715
=> Remove workarounds etc. regarding sbox-issue 1715
